### ISSUE TITLE
Wrong request headers(cookie)

### ISSUE THREAD

**Issue by senyaak** [jsargiot/restman#20]
If you want to send a request without headers and you have cookies for this site, the cookies will be send too. This is not what I expect!

**Comment by jsargiot** [comment]
I'll look into this. Setting cookies is not trivial because for security reason are handled by the browser, there is a `cookie` api for extensions but I don't think we could clear the cookies just for the extension without affecting normal browsing.

Allowing to open the extension in incognito mode could work...

**Comment by senyaarseniy** [comment]
> Allowing to open the extension in incognito mode could work...

thx.

It will enough if users will see that cookies are send too.

**Comment by jsargiot** [comment]
I'm closing this issue since opening the extension in incognito mode already helps on the original problem.

@yarx1988, your problem seems to be that the endpoint is responding with an unauthorized http response, if your problem persists, please open a new issue.
