### ISSUE TITLE
Repeated requests in History

### ISSUE THREAD

**Issue by vkirilkov** [jsargiot/restman#7]
Hallo,
Can you please delete all same requests automatically from History? This will decrease my big list significatly:)

**Comment by jsargiot** [comment]
Noted, this will be included in the next version, which should be released in the next couple of weeks. Thanks.

**Comment by jsargiot** [comment]
This is fixed in version 0.3, requests won't be added to the history a second (or third, or nth) time if url, headers and body are the same.

I'm afraid this won't clean entries already in the history.

To clean up polluted history you can use this gist: https://gist.github.com/jsargiot/615e30c7b08a68d1f3c7 (instructions inline). WARNING: Please backup your IndexedDB before running the snippet.
